package com.isuranga.cloud_note.model;

public enum Category {
    CHEMICAL_ENGINEERING_TECHNOLOGY,
    CIVIL_ENGINEERING_TECHNOLOGY,
    ELECTRICAL_ENGINEERING_TECHNOLOGY,
    ELECTRONIC_AND_TELECOMMUNICATION_ENGINEERING_TECHNOLOGY,
    INFORMATION_TECHNOLOGY,
    MECHANICAL_ENGINEERING_TECHNOLOGY,
    MARINE_TECHNOLOGY,
    NAUTICAL_STUDIES,
    POLYMER_TECHNOLOGY,
    TEXTILE_AND_CLOTHING_TECHNOLOGY
}